/*
 *  Copyright (c) 2008 Aur Saraf
 *  See the file "license.terms" for information on usage and redistribution
 *  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 * 
 *     $Id$
 * Function pointers for sdl_gfx functions
 */

{ SDL_PixelColorFunc, "SDL_PixelColorFunc", es_pixelColor },
{ SDL_PixelRGBAFunc, "SDL_PixelRGBAFunc", es_pixelRGBA },
{ SDL_HlineColorFunc, "SDL_HlineColorFunc", es_hlineColor },
{ SDL_HlineRGBAFunc, "SDL_HlineRGBAFunc", es_hlineRGBA },
{ SDL_VlineColorFunc, "SDL_VlineColorFunc", es_vlineColor },
{ SDL_VlineRGBAFunc, "SDL_VlineRGBAFunc", es_vlineRGBA },
{ SDL_RectangleColorFunc, "SDL_RectangleColorFunc", es_rectangleColor },
{ SDL_RectangleRGBAFunc, "SDL_RectangleRGBAFunc", es_rectangleRGBA },
{ SDL_BoxColorFunc, "SDL_BoxColorFunc", es_boxColor },
{ SDL_BoxRGBAFunc, "SDL_BoxRGBAFunc", es_boxRGBA },
{ SDL_LineColorFunc, "SDL_LineColorFunc", es_lineColor },
{ SDL_LineRGBAFunc, "SDL_LineRGBAFunc", es_lineRGBA },
{ SDL_AalineColorFunc, "SDL_AalineColorFunc", es_aalineColor },
{ SDL_AalineRGBAFunc, "SDL_AalineRGBAFunc", es_aalineRGBA },
{ SDL_CircleColorFunc, "SDL_CircleColorFunc", es_circleColor },
{ SDL_CircleRGBAFunc, "SDL_CircleRGBAFunc", es_circleRGBA },
{ SDL_ArcColorFunc, "SDL_ArcColorFunc", es_arcColor },
{ SDL_ArcRGBAFunc, "SDL_ArcRGBAFunc", es_arcRGBA },
{ SDL_AacircleColorFunc, "SDL_AacircleColorFunc", es_aacircleColor },
{ SDL_AacircleRGBAFunc, "SDL_AacircleRGBAFunc", es_aacircleRGBA },
{ SDL_FilledCircleColorFunc, "SDL_FilledCircleColorFunc", es_filledCircleColor },
{ SDL_FilledCircleRGBAFunc, "SDL_FilledCircleRGBAFunc", es_filledCircleRGBA },
{ SDL_EllipseColorFunc, "SDL_EllipseColorFunc", es_ellipseColor },
{ SDL_EllipseRGBAFunc, "SDL_EllipseRGBAFunc", es_ellipseRGBA },
{ SDL_AaellipseColorFunc, "SDL_AaellipseColorFunc", es_aaellipseColor },
{ SDL_AaellipseRGBAFunc, "SDL_AaellipseRGBAFunc", es_aaellipseRGBA },
{ SDL_FilledEllipseColorFunc, "SDL_FilledEllipseColorFunc", es_filledEllipseColor },
{ SDL_FilledEllipseRGBAFunc, "SDL_FilledEllipseRGBAFunc", es_filledEllipseRGBA },
{ SDL_PieColorFunc, "SDL_PieColorFunc", es_pieColor },
{ SDL_PieRGBAFunc, "SDL_PieRGBAFunc", es_pieRGBA },
{ SDL_FilledPieColorFunc, "SDL_FilledPieColorFunc", es_filledPieColor },
{ SDL_FilledPieRGBAFunc, "SDL_FilledPieRGBAFunc", es_filledPieRGBA },
{ SDL_TrigonColorFunc, "SDL_TrigonColorFunc", es_trigonColor },
{ SDL_TrigonRGBAFunc, "SDL_TrigonRGBAFunc", es_trigonRGBA },
{ SDL_AatrigonColorFunc, "SDL_AatrigonColorFunc", es_aatrigonColor },
{ SDL_AatrigonRGBAFunc, "SDL_AatrigonRGBAFunc", es_aatrigonRGBA },
{ SDL_FilledTrigonColorFunc, "SDL_FilledTrigonColorFunc", es_filledTrigonColor },
{ SDL_FilledTrigonRGBAFunc, "SDL_FilledTrigonRGBAFunc", es_filledTrigonRGBA },
{ SDL_PolygonColorFunc, "SDL_PolygonColorFunc", es_polygonColor },
{ SDL_PolygonRGBAFunc, "SDL_PolygonRGBAFunc", es_polygonRGBA },
{ SDL_AapolygonColorFunc, "SDL_AapolygonColorFunc", es_aapolygonColor },
{ SDL_AapolygonRGBAFunc, "SDL_AapolygonRGBAFunc", es_aapolygonRGBA },
{ SDL_FilledPolygonColorFunc, "SDL_FilledPolygonColorFunc", es_filledPolygonColor },
{ SDL_FilledPolygonRGBAFunc, "SDL_FilledPolygonRGBAFunc", es_filledPolygonRGBA },
{ SDL_TexturedPolygonFunc, "SDL_TexturedPolygonFunc", es_texturedPolygon },
{ SDL_TexturedPolygonMTFunc, "SDL_TexturedPolygonMTFunc", es_texturedPolygonMT },
{ SDL_BezierColorFunc, "SDL_BezierColorFunc", es_bezierColor },
{ SDL_BezierRGBAFunc, "SDL_BezierRGBAFunc", es_bezierRGBA },
{ SDL_CharacterColorFunc, "SDL_CharacterColorFunc", es_characterColor },
{ SDL_CharacterRGBAFunc, "SDL_CharacterRGBAFunc", es_characterRGBA },
{ SDL_StringColorFunc, "SDL_StringColorFunc", es_stringColor },
{ SDL_StringRGBAFunc, "SDL_StringRGBAFunc", es_stringRGBA },
{ SDL_GfxPrimitivesSetFontFunc, "SDL_GfxPrimitivesSetFontFunc", es_gfxPrimitivesSetFont },
