/*
 *  Copyright (c) 2008 Aur Saraf
 *  See the file "license.terms" for information on usage and redistribution
 *  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 * 
 *     $Id$
 * Function pointers for sdl_gfx functions
 */

{ SDL_InitFunc, "SDL_InitFunc", es_init },
{ SDL_PixelColorFunc, "SDL_PixelColorFunc", pixelColor },
{ SDL_PixelRGBAFunc, "SDL_PixelRGBAFunc", pixelRGBA },
{ SDL_HlineColorFunc, "SDL_HlineColorFunc", hlineColor },
{ SDL_HlineRGBAFunc, "SDL_HlineRGBAFunc", hlineRGBA },
{ SDL_VlineColorFunc, "SDL_VlineColorFunc", vlineColor },
{ VlineRGBAFunc, "VlineRGBAFunc", vlineRGBA },
{ SDL_RectangleColorFunc, "SDL_RectangleColorFunc", rectangleColor },
{ SDL_RectangleRGBAFunc, "SDL_RectangleRGBAFunc", rectangleRGBA },
{ SDL_BoxColorFunc, "SDL_BoxColorFunc", boxColor },
{ SDL_BoxRGBAFunc, "SDL_BoxRGBAFunc", boxRGBA },
{ SDL_LineColorFunc, "SDL_LineColorFunc", lineColor },
{ SDL_LineRGBAFunc, "SDL_LineRGBAFunc", lineRGBA },
{ SDL_AalineColorFunc, "SDL_AalineColorFunc", aalineColor },
{ SDL_AalineRGBAFunc, "SDL_AalineRGBAFunc", aalineRGBA },
{ SDL_CircleColorFunc, "SDL_CircleColorFunc", circleColor },
{ SDL_CircleRGBAFunc, "SDL_CircleRGBAFunc", circleRGBA },
{ SDL_ArcColorFunc, "SDL_ArcColorFunc", arcColor },
{ SDL_ArcRGBAFunc, "SDL_ArcRGBAFunc", arcRGBA },
{ SDL_AacircleColorFunc, "SDL_AacircleColorFunc", aacircleColor },
{ SDL_AacircleRGBAFunc, "SDL_AacircleRGBAFunc", aacircleRGBA },
{ SDL_FilledCircleColorFunc, "SDL_FilledCircleColorFunc", filledCircleColor },
{ SDL_FilledCircleRGBAFunc, "SDL_FilledCircleRGBAFunc", filledCircleRGBA },
{ SDL_EllipseColorFunc, "SDL_EllipseColorFunc", ellipseColor },
{ SDL_EllipseRGBAFunc, "SDL_EllipseRGBAFunc", ellipseRGBA },
{ SDL_AaellipseColorFunc, "SDL_AaellipseColorFunc", aaellipseColor },
{ SDL_AaellipseRGBAFunc, "SDL_AaellipseRGBAFunc", aaellipseRGBA },
{ SDL_FilledEllipseColorFunc, "SDL_FilledEllipseColorFunc", filledEllipseColor },
{ SDL_FilledEllipseRGBAFunc, "SDL_FilledEllipseRGBAFunc", filledEllipseRGBA },
{ SDL_PieColorFunc, "SDL_PieColorFunc", pieColor },
{ SDL_PieRGBAFunc, "SDL_PieRGBAFunc", pieRGBA },
{ SDL_FilledPieColorFunc, "SDL_FilledPieColorFunc", filledPieColor },
{ SDL_FilledPieRGBAFunc, "SDL_FilledPieRGBAFunc", filledPieRGBA },
{ SDL_TrigonColorFunc, "SDL_TrigonColorFunc", trigonColor },
{ SDL_TrigonRGBAFunc, "SDL_TrigonRGBAFunc", trigonRGBA },
{ SDL_AatrigonColorFunc, "SDL_AatrigonColorFunc", aatrigonColor },
{ SDL_AatrigonRGBAFunc, "SDL_AatrigonRGBAFunc", aatrigonRGBA },
{ SDL_FilledTrigonColorFunc, "SDL_FilledTrigonColorFunc", filledTrigonColor },
{ SDL_FilledTrigonRGBAFunc, "SDL_FilledTrigonRGBAFunc", filledTrigonRGBA },
{ SDL_PolygonColorFunc, "SDL_PolygonColorFunc", polygonColor },
{ SDL_PolygonRGBAFunc, "SDL_PolygonRGBAFunc", polygonRGBA },
{ SDL_AapolygonColorFunc, "SDL_AapolygonColorFunc", aapolygonColor },
{ SDL_AapolygonRGBAFunc, "SDL_AapolygonRGBAFunc", aapolygonRGBA },
{ SDL_FilledPolygonColorFunc, "SDL_FilledPolygonColorFunc", filledPolygonColor },
{ SDL_FilledPolygonRGBAFunc, "SDL_FilledPolygonRGBAFunc", filledPolygonRGBA },
{ SDL_TexturedPolygonFunc, "SDL_TexturedPolygonFunc", texturedPolygon },
{ SDL_TexturedPolygonMTFunc, "SDL_TexturedPolygonMTFunc", texturedPolygonMT },
{ SDL_BezierColorFunc, "SDL_BezierColorFunc", bezierColor },
{ SDL_BezierRGBAFunc, "SDL_BezierRGBAFunc", bezierRGBA },
{ SDL_CharacterColorFunc, "SDL_CharacterColorFunc", characterColor },
{ SDL_CharacterRGBAFunc, "SDL_CharacterRGBAFunc", characterRGBA },
{ SDL_StringColorFunc, "SDL_StringColorFunc", stringColor },
{ SDL_StringRGBAFunc, "SDL_StringRGBAFunc", stringRGBA },
{ SDL_GfxPrimitivesSetFontFunc, "SDL_GfxPrimitivesSetFontFunc", gfxPrimitivesSetFont },
